name: Deploy Node Todo App using Private Runner

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      imageTag:
        description: "Docker Image Tag"
        required: true
        default: "latest"

      environment:
        description: "Deployment Environment"
        required: true
        default: "dev"

jobs:
  build-deploy:
    runs-on: self-hosted

    env:
      AWS_REGION: eu-north-1
      ECR_REGISTRY: 577002943781.dkr.ecr.eu-north-1.amazonaws.com
      ECR_REPOSITORY: node/app

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Workflow Parameters
        run: |
          IMAGE_TAG="${{ github.event.inputs.imageTag }}"
          ENVIRONMENT="${{ github.event.inputs.environment }}"

          if [ -z "$IMAGE_TAG" ]; then
            IMAGE_TAG="latest"
          fi

          if [ -z "$ENVIRONMENT" ]; then
            ENVIRONMENT="dev"
          fi

          echo "Image Tag: $IMAGE_TAG"
          echo "Environment: $ENVIRONMENT"

      - name: Login to Amazon ECR using IAM Role
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build Docker Image
        run: |
          IMAGE_TAG="${{ github.event.inputs.imageTag }}"
          if [ -z "$IMAGE_TAG" ]; then
            IMAGE_TAG="latest"
          fi

          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

      - name: Tag Docker Image
        run: |
          IMAGE_TAG="${{ github.event.inputs.imageTag }}"
          if [ -z "$IMAGE_TAG" ]; then
            IMAGE_TAG="latest"
          fi

          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push Docker Image to Amazon ECR
        run: |
          IMAGE_TAG="${{ github.event.inputs.imageTag }}"
          if [ -z "$IMAGE_TAG" ]; then
            IMAGE_TAG="latest"
          fi

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to Amazon ECS
        run: |
          aws ecs update-service \
            --cluster NodeCluster \
            --service node-todo-app-td-service-hdy5v8sf \
            --force-new-deployment \
            --region $AWS_REGION
