name: Deploy Node Todo App using Private Runner

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      imageTag:
        description: "Docker Image Tag"
        required: true
        default: "latest"

jobs:
  build-deploy:
    runs-on: self-hosted

    env:
      AWS_REGION: eu-north-1
      ECR_REGISTRY: 577002943781.dkr.ecr.eu-north-1.amazonaws.com
      ECR_REPOSITORY: node/app

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Workflow Inputs
        run: |
          echo "Image Tag: ${{ github.event.inputs.imageTag || 'latest' }}"

      - name: Login to Amazon ECR using IAM Role
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY:${{ github.event.inputs.imageTag || 'latest' }} .

      - name: Tag Docker Image
        run: |
          docker tag $ECR_REPOSITORY:${{ github.event.inputs.imageTag || 'latest' }} \
          $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.event.inputs.imageTag || 'latest' }}

      - name: Push Docker Image to Amazon ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.event.inputs.imageTag || 'latest' }}

      - name: Deploy to Amazon ECS
        run: |
          aws ecs update-service \
            --cluster NodeCluster \
            --service node-todo-app-td-service-hdy5v8sf \
            --force-new-deployment \
            --region $AWS_REGION
