name: Test Multiple Self Hosted Runners

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  dev-job:
    runs-on:
      - self-hosted
      - dev

    steps:
      - uses: actions/checkout@v4

      - name: Test Dev Runner
        run: |
          echo "Running on DEV Runner"
          hostname

  qa-job:
    runs-on:
      - self-hosted
      - qa

    steps:
      - uses: actions/checkout@v4

      - name: Test QA Runner
        run: |
          echo "Running on QA Runner"
          hostname
